name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Isso vai disparar o workflow para tags que seguem o padrão v0.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}  # Usa a tag que disparou o workflow
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes
          - Describe your changes here
        draft: false
        prerelease: false

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public
